Hochladen des Projektes
tobi1196/INFORE3 pull request #16
Opened 2017-10-20 16:56 UTC by tobi1196

2017-10-22 16:54 UTC, nicolaiparlog commented
Es ist nicht ganz klar, welche Issues ihr hier genau lösen wollt, aber der Anwesenheit von `HelloWorldTest.kt` entnehme ich, dass die Testintegration auch dazu gehört. (Bitte gebt im PR immer an, welche Issues er bearbeitet).

2017-10-22 16:58 UTC, nipafx requested changes

2017-10-22 16:58 UTC, nicolaiparlog commented on pom.xml
> +    </properties>
Bitte legt noch `<project.build.sourceEncoding>` auf `UTF-8`, um die Maven-Warnungen loszuwerden:

> [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

2017-10-22 16:58 UTC, nicolaiparlog commented on pom.xml
> +        <dependency>
Diese Dependency kann raus - wir verwenden _kotlin-test_ nicht.

2017-10-22 16:58 UTC, nicolaiparlog commented on pom.xml
> +        <plugins>
Die erstellte JAR ist noch nicht ausführbar mit `java -jar target/INFORE3-1.0-SNAPSHOT.jar` - dazu fehlt noch der gesamte _maven-assembly-plugin_ Block. Das könnt ihr entweder in diesem PR machen oder dafür ein neues Ticket erstellen.

2017-10-22 16:58 UTC, nicolaiparlog commented on src/main/java/HelloWorld.kt
> +fun main(args : Array<String>){
Diese Datei gehört nicht in `src/main/java` sondern in `src/main/kotlin` - damit das funktioniert, müsst ihr die POM noch ein bisschen erweitern (siehe Vorlesung).

2017-10-22 16:58 UTC, nicolaiparlog commented on src/test/java/HelloWorldTest.kt
> +class HelloWorldTest {
Diese Datei gehört nicht in `src/test/java` sondern in `src/test/kotlin` - damit das funktioniert, müsst ihr die POM noch ein bisschen erweitern (siehe Vorlesung).

2017-10-28 14:12 UTC, tobi1196 commented
@nicolaiparlog haben das Projekt überarbeitet

2017-10-28 14:13 UTC, tobi1196 commented
Issue #6 wird damit abgeschlossen

2017-10-28 20:25 UTC, nipafx approved these changes

2017-10-28 20:25 UTC, nicolaiparlog commented
:+1:

2017-10-29 10:58 UTC, adrianstarkbaum commented
Hochladen des Projektes damit Abschluss von #6 und #7 jetzt bearbeiten

2017-10-29 10:58 UTC, merged

2017-10-30 13:23 UTC, tobi1196 commented
#8 wurde damit auch abgeschlossen