Hochladen des Projektes 2.0
tobi1196/INFORE3 pull request #24
Opened 2017-10-31 11:54 UTC by tobi1196

#23 wird damit bearbeitet

@nicolaiparlog bitte drüber schauen

2017-10-31 14:04 UTC, tobi1196 commented
Entschuldigung Sie bitte, ich kam ausversehen auf das Feld für die request Anfrage

2017-10-31 22:03 UTC, nipafx requested changes

2017-10-31 22:03 UTC, nicolaiparlog commented on src/main/kotlin/RailNetwork.kt
> +            var delayed = false
Die Bestimmung ob ein Segment ausgelastet ist, kannst du in `RailSegment` verschieben, z.B. als `checkDelay` oder so. Damit kannst du die dortigen Methoden `getCapacity`, `getTrainCount`, und `setTrainDelayed`.

2017-10-31 22:03 UTC, nicolaiparlog commented on src/main/kotlin/RailNetwork.kt
> +    fun getNetworkStatus():List<List<String>>{
Der Status des Netzwerks ist in den Zügen festgehalten, d.h. du kannst ihn da ablesen und direkt in auf die Konsole schreiben. Mach das am besten in `Main` - dann brauchst du nicht diese komplexe `List<List<String>>` anlegen.

2017-10-31 22:03 UTC, nicolaiparlog commented on src/main/kotlin/Main.kt
> +    var dataIO = DataIO()
Die Methode macht genau das, was `external` machen soll, d.h. Daten aus CSV lesen, simulieren und wieder rein schreiben. Sehr gut. Verschieb den Code einfach in eine neue Methode `external` und der Teil ist erledigt.

Fehlt noch `scenario`, prinzipiell das gleiche aber ohne CSV machen soll, d.h. eine Simulation mit willkürlich gewählten Daten erstellen, simulieren und Ergebnisse auf die Konsole schreiben.

2017-11-01 16:28 UTC, tobi1196 commented
@nicolaiparlog Verbesserungen wurden vorgenommen

2017-11-01 22:35 UTC, merged

2017-11-01 22:37 UTC, tobi1196 commented
Haben das Projekt nach unserer Überarbeitung nun gemerget da wir morgen leider zeitlich eingeschrenkt sind und nicht mehr weiter arbeiten können, aber noch Projekt v2.0 releasen wollten

2017-11-01 23:01 UTC, tobi1196 commented
Damit abgeschlossen #25 #26 #27 #28